# =======================================================================
# Author: Cesar Ordonez
# Date: 12 Jan 2023
# Config file to process transect with different models
# =======================================================================

# =======================================================================
# Inputs path and filenames
# =======================================================================
path: 'Data'
path_res: 'Results'

# =======================================================================
# Model configuration
# =======================================================================
ConfModel:
  Kh_model: 'P' #('P' : Peeters 2005, 'L': Lawrence 1995)
  k600_model: 'kAVG' # ('VP : Vachon & Prairie, 'CC': Cole & Caraco)
  t_end: 30 # days
  dt: 0.005 # days
  dr: 1 # meters
  mode_model:
    mode: 'OPT'
    var: 'PNET'

lakes:
  Testlake: ['20180616', '20180902'] #, '20190720']
  Testlake2: ['20180616'] #, '20190720']
    #Noir: ['20180620', '20180904', '20190724']
    #Lioson: ['20180624', '20180829', '20190717']
    #Chavonnes: ['20180618', '20180905', '20190723']

Montecarlo:
  perform: True
  N: 10.1
